# Generated by Django 4.2.2 on 2023-06-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(choices=[('SeaFood', 'SeaFood'), ('Japanese', 'Japanese'), ('NonSusu', 'NonSusu'), ('Sayuran', 'Sayuran'), ('Bakery', 'Bakery'), ('FastFood', 'FastFood'), ('Indian', 'Indian'), ('Rebus', 'Rebus'), ('Goreng', 'Goreng'), ('Pasta', 'Pasta'), ('Bakar', 'Bakar'), ('HomeCook', 'HomeCook'), ('Profesional', 'Profesional')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
