# Generated by Django 4.2.2 on 2023-06-10 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_gender_user_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(to='account.interest'),
        ),
    ]
