# Generated by Django 4.2.2 on 2023-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Men', 'Men'), ('Women', 'Women')], default='Unknown', max_length=10),
        ),
    ]
