# Generated by Django 4.2.2 on 2023-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_ingredient_number'),
        ('account', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='recipe.recipe'),
        ),
    ]
