# Generated by Django 4.2.2 on 2023-07-02 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('Q', 'Q'), ('Gram', 'Gram'), ('Liter', 'Liter'), ('Sendok', 'Sendok'), ('Buah', 'Buah'), ('Sachet', 'Sachet')], default='Q', max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('ingredient_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('method_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='recipe-images/')),
                ('duration', models.IntegerField(default=0)),
                ('portion', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('Pemula', 'Pemula'), ('Pro', 'Pro')], max_length=10)),
                ('view', models.IntegerField(default=0)),
                ('fav', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ManyToManyField(blank=True, related_name='guest', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ManyToManyField(to='recipe.ingredient')),
                ('method', models.ManyToManyField(to='recipe.method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='recipe_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_fk', to='recipe.recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_fk', to='recipe.recipe'),
        ),
    ]
