# Generated by Django 4.2.2 on 2023-07-04 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.coreingredient'),
        ),
    ]
