# Generated by Django 4.2.2 on 2023-07-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_coreingredient_alter_ingredient_ingredient_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_text',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='coreingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.coreingredient'),
        ),
    ]
