# Generated by Django 4.2.2 on 2023-06-11 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Pemula', 'Pemula'), ('Pro', 'Pro')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='portion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='recipe.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.ManyToManyField(to='recipe.method'),
        ),
    ]
