# Generated by Django 4.2.2 on 2023-07-04 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_ingredient_ingredient_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='coreingredient',
            name='categoryingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.categoryingredient'),
        ),
    ]
