# Generated by Django 4.2.2 on 2023-06-11 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_ingredient_method_recipe_calories_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_fk', to='recipe.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='recipe_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='method_fk', to='recipe.recipe'),
            preserve_default=False,
        ),
    ]
