# Generated by Django 4.2.2 on 2023-06-11 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_ingredient_recipe_fk_method_recipe_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_text', models.CharField(max_length=50)),
                ('ingredient_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_fk', to='recipe.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit_mtm',
            field=models.ManyToManyField(to='recipe.unitingredient'),
        ),
    ]
