# Generated by Django 4.2.2 on 2023-06-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_unitingredient_ingredient_unit_mtm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit_mtm',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('Q', 'Q'), ('Gram', 'Gram'), ('Liter', 'Liter'), ('Sendok', 'Sendok'), ('Buah', 'Buah'), ('Sachet', 'Sachet')], default='Q', max_length=10),
        ),
        migrations.DeleteModel(
            name='UnitIngredient',
        ),
    ]
