# Generated by Django 4.2.2 on 2023-07-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
