# Generated by Django 4.2.2 on 2023-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_remove_ingredient_unit_mtm_ingredient_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
