# Generated by Django 4.2.2 on 2023-07-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_ingredient_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(blank=True, related_name='ingredient', to='recipe.ingredient'),
        ),
    ]
