# Generated by Django 4.2.2 on 2023-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
