# Generated by Django 4.2.2 on 2023-07-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_recipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.ManyToManyField(blank=True, related_name='method', to='recipe.method'),
        ),
    ]
