# Generated by Django 4.2.2 on 2023-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_recipe_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='categoryingredient',
            field=models.ManyToManyField(blank=True, related_name='categoryingredient', to='recipe.categoryingredient'),
        ),
    ]
