# Generated by Django 4.2.2 on 2023-06-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_ingredient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
