# Generated by Django 4.2.2 on 2023-06-30 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0011_recipe_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='guest',
            field=models.ManyToManyField(blank=True, related_name='guest', to=settings.AUTH_USER_MODEL),
        ),
    ]
