# Generated by Django 4.2.2 on 2023-07-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_recipe_categoryingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
