# Generated by Django 4.2.2 on 2023-07-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_ingredient_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='note',
        ),
    ]
