# Generated by Django 4.2.2 on 2023-07-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0019_ingredient_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='coreingredient',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='note',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='categoryingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='status',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='recipe.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.ManyToManyField(to='recipe.method'),
        ),
        migrations.DeleteModel(
            name='CategoryIngredient',
        ),
        migrations.DeleteModel(
            name='CoreIngredient',
        ),
    ]
