# Generated by Django 4.2.2 on 2023-07-08 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0023_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='category_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='core_fk', to='recipe.category'),
            preserve_default=False,
        ),
    ]
