# Generated by Django 4.2.2 on 2023-07-08 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0024_core_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='core',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_core', to='recipe.core'),
            preserve_default=False,
        ),
    ]
