# Generated by Django 4.2.2 on 2023-07-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0025_ingredient_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='core',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_core', to='recipe.core'),
        ),
    ]
