# Generated by Django 4.2.2 on 2023-07-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0026_alter_ingredient_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_fk', to='recipe.category'),
        ),
    ]
