# Generated by Django 4.2.2 on 2023-07-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0027_alter_core_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(to='recipe.category'),
        ),
    ]
