# Generated by Django 4.2.2 on 2023-07-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0028_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='core',
            field=models.ManyToManyField(blank=True, related_name='category_core', to='recipe.core'),
        ),
    ]
