# Generated by Django 4.2.2 on 2023-07-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0029_category_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
