# Generated by Django 4.2.2 on 2023-07-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0030_ingredient_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_hidden_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_hidden_like',
            field=models.BooleanField(default=False),
        ),
    ]
