# Generated by Django 4.2.2 on 2023-07-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_favorite_user_last_view'),
        ('recipe', '0033_alter_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='interest',
            field=models.ManyToManyField(to='account.interest'),
        ),
    ]
