# Generated by Django 4.2.2 on 2023-07-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_favorite_user_last_view'),
        ('recipe', '0034_recipe_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='interest',
            field=models.ManyToManyField(blank=True, to='account.interest'),
        ),
    ]
