version: '3'
services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: recheffapp
      MYSQL_DATABASE: recheffapp
      MYSQL_USER: recheffapp
      MYSQL_PASSWORD: recheffapp
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
      --innodb-use-native-aio=0
      --innodb-flush-method=fsync
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  dbdata: